DROP Database IF EXISTS facebook_db;

CREATE Database facebook_db;
USE facebook_db;

CREATE TABLE users (
	user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	username VARCHAR(50) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	date_of_birth DATE NOT NULL,
	gender ENUM('Male', 'Female', 'Others') NOT NULL,
	bio TEXT,
	profile_picture_url VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);
CREATE TABLE posts (
	post_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	content TEXT,
	media_url VARCHAR(255),
	media_type ENUM('TEXT', 'IMAGE', 'VIDEO') DEFAULT 'TEXT',
	privacy ENUM('PUBLIC', 'FRIENDS', 'CUSTOM') DEFAULT 'FRIENDS',	
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE likes (
	like_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	post_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	UNIQUE (post_id, user_id),
	FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
	
);

CREATE TABLE comments (
	comment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	post_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	content TEXT NOT NULL,	
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
	
);

CREATE TABLE friend_requests (
	request_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	sender_id BIGINT NOT NULL,
	receiver_id BIGINT NOT NULL,
	status ENUM('PENDING', 'ACCEPTED', 'DECLINED') DEFAULT 'PENDING',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE (sender_id, receiver_id),	
	FOREIGN KEY (sender_id) REFERENCES users(user_id) ON DELETE CASCADE,
	FOREIGN KEY (receiver_id) REFERENCES users(user_id) ON DELETE CASCADE
);


CREATE TABLE friends (
	user_id BIGINT NOT NULL,
	friend_id BIGINT NOT NULL,
--	is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (user_id, friend_id),	
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
	FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE
);



CREATE TABLE sessions (
	session_id BIGINT PRIMARY KEY AUTO_INCREMENT,	
	user_id BIGINT NOT NULL,	
	token VARCHAR(255) UNIQUE NOT NULL,	
	expiry_time TIMESTAMP NOT NULL,	
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 	
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


CREATE TABLE user_photos (
	photo_id BIGINT PRIMARY KEY AUTO_INCREMENT,	
	user_id BIGINT NOT NULL,
	photo LONGBLOB NOT NULL,		
	uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  	
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE security_questions(
	question_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	question VARCHAR(255) NOT NULL,
	answer_hash VARCHAR(255) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);


CREATE TABLE post_privacy(
	privacy_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	post_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES
	posts(post_id) ON DELETE CASCADE,
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES
	users(user_id) ON DELETE CASCADE
);


CREATE TABLE blocked_users(
	blocked_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	blocked_user_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_block_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT fk_blocked FOREIGN KEY (blocked_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
	UNIQUE (user_id, blocked_user_id)
);

